"""Phase 1 Prompts: Paper ingestion, summarization, critique, and mechanism extraction."""

from .paper_summarizer import (
    CONTEXT_EXTRACTOR_SYSTEM_PROMPT,
    CONTEXT_EXTRACTOR_USER_PROMPT,
    CONTEXT_EXTRACTOR_REVISION_SYSTEM_PROMPT,
    CONTEXT_EXTRACTOR_REVISION_USER_PROMPT,
)
from .paper_summarizer_critic import (
    SUMMARIZER_CRITIC_SYSTEM_PROMPT,
    SUMMARIZER_CRITIC_USER_PROMPT,
)
from .mechanism_extractor import (
    MECHANISM_EXTRACTOR_SYSTEM_PROMPT,
    MECHANISM_EXTRACTOR_USER_PROMPT,
)

__all__ = [
    "CONTEXT_EXTRACTOR_SYSTEM_PROMPT",
    "CONTEXT_EXTRACTOR_USER_PROMPT",
    "CONTEXT_EXTRACTOR_REVISION_SYSTEM_PROMPT",
    "CONTEXT_EXTRACTOR_REVISION_USER_PROMPT",
    "SUMMARIZER_CRITIC_SYSTEM_PROMPT",
    "SUMMARIZER_CRITIC_USER_PROMPT",
    "MECHANISM_EXTRACTOR_SYSTEM_PROMPT",
    "MECHANISM_EXTRACTOR_USER_PROMPT",
]
