"""Phase 2 Prompts: Open Problem Formulation workflow."""

from .agenda_creator import AGENDA_CREATOR_SYSTEM, AGENDA_CREATOR_PROMPT
from .field_expert import (
    FIELD_EXPERT_SYSTEM,
    FIELD_EXPERT_R1_PROMPT,
    FIELD_EXPERT_R2_PROMPT,
    FIELD_EXPERT_R2_REVISION_PROMPT,
)
from .expert_r2_critic import EXPERT_R2_CRITIC_SYSTEM, EXPERT_R2_CRITIC_PROMPT
from .report_generator import REPORT_GENERATOR_SYSTEM, REPORT_GENERATOR_PROMPT
from .mechanism_updater import MECHANISM_UPDATER_SYSTEM, MECHANISM_UPDATER_PROMPT
from .final_judge import JUDGE_SYSTEM, FINAL_JUDGE_PROMPT
from .problem_ranker import PROBLEM_RANKER_SYSTEM, PROBLEM_RANKER_PROMPT

__all__ = [
    # Agenda Creator
    "AGENDA_CREATOR_SYSTEM",
    "AGENDA_CREATOR_PROMPT",
    # Field Experts
    "FIELD_EXPERT_SYSTEM",
    "FIELD_EXPERT_R1_PROMPT",
    "FIELD_EXPERT_R2_PROMPT",
    "FIELD_EXPERT_R2_REVISION_PROMPT",
    # Expert R2 Critic
    "EXPERT_R2_CRITIC_SYSTEM",
    "EXPERT_R2_CRITIC_PROMPT",
    # Report
    "REPORT_GENERATOR_SYSTEM",
    "REPORT_GENERATOR_PROMPT",
    # Mechanism Updater
    "MECHANISM_UPDATER_SYSTEM",
    "MECHANISM_UPDATER_PROMPT",
    # Judge
    "JUDGE_SYSTEM",
    "FINAL_JUDGE_PROMPT",
    # Problem Ranker
    "PROBLEM_RANKER_SYSTEM",
    "PROBLEM_RANKER_PROMPT",
]
