from pydantic import BaseModel, Field
from typing import List



class Proposal(BaseModel):
    xml: str = Field(description="The XML string representation of the proposal.")

    

class AgentBrainstormResult(BaseModel):
    xml_list: List[Proposal] = Field(description="The list containing a single XML string representing all new proposals generated by the agent.")
    

class ScrutinyResult(BaseModel):
    xml: str = Field(description="The XML string representing the entire updated shared memory after scrutiny.")

